name: Build Site

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *" # 5AM EST

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUBY_YJIT_ENABLE: "1"
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install minify
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab the latest version
          repo: tdewolff/minify
          tag: v2.24.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Build docs
        run: bundle exec rake build
        env:
          OPEN_METEO_API_KEY: ${{ secrets.OPEN_METEO_API_KEY }}
          OPEN_METEO_API_URL: ${{ secrets.OPEN_METEO_API_URL }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 945954ae6af55e6e4af004fb7772fdc5
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy docs/ --project-name followthesnow
